# Generated by Django 4.2.3 on 2023-07-25 11:33

import datetime
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gear_type', models.CharField(choices=[('auto', '자동'), ('manual', '수동')], default='auto', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'myuser',
            },
        ),
        migrations.CreateModel(
            name='OperationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('operation_day', models.DateField(default=datetime.date(2023, 7, 25))),
            ],
            options={
                'db_table': 'operation_day',
            },
        ),
        migrations.CreateModel(
            name='OperationOnOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('operation_onoff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'operation_onoff',
            },
        ),
        migrations.CreateModel(
            name='PriceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'price_file',
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('start_section', models.CharField(default='', max_length=255)),
                ('end_section', models.CharField(default='', max_length=255)),
                ('calculated_price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'price_table',
            },
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('start_address', models.CharField(default='', max_length=255)),
                ('end_address', models.CharField(default='', max_length=255)),
                ('start_section', models.CharField(default='', max_length=255)),
                ('end_section', models.CharField(default='', max_length=255)),
                ('order_kind', models.CharField(choices=[('order', '주문'), ('change', '변경'), ('cancel', '취소')], default='order', max_length=255)),
                ('operation_day', models.DateField(default=datetime.date(2023, 7, 25))),
                ('order_type', models.BooleanField(default=True)),
                ('is_hide', models.BooleanField(default=False)),
                ('calculated_price', models.IntegerField(default=12)),
                ('start_x', models.CharField(default='', max_length=255)),
                ('start_y', models.CharField(default='', max_length=255)),
                ('end_x', models.CharField(default='', max_length=255)),
                ('end_y', models.CharField(default='', max_length=255)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orderdata',
            },
        ),
        migrations.CreateModel(
            name='AddressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('raw_address', models.CharField(default='', max_length=255)),
                ('trans_address', models.CharField(default='', max_length=255)),
                ('road_address', models.CharField(default='', max_length=255)),
                ('category_name', models.CharField(default='', max_length=255)),
                ('section_name', models.CharField(default='', max_length=255)),
                ('location_x', models.CharField(default='', max_length=255)),
                ('location_y', models.CharField(default='', max_length=255)),
                ('address_type', models.CharField(choices=[('start', '출발지'), ('end', '목적지')], max_length=255)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='history_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'addrees history',
            },
        ),
    ]
