# Generated by Django 4.2.3 on 2023-08-02 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calldriverapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='bidding_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operationday',
            name='operation_day',
            field=models.DateField(default=datetime.date(2023, 8, 2)),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='operation_day',
            field=models.DateField(default=datetime.date(2023, 8, 2)),
        ),
    ]
