# Generated by Django 4.2.3 on 2023-07-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calldriverapp', '0002_addresshistory_customer_orderdata_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
