# Generated by Django 4.2.3 on 2023-07-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calldriverapp', '0004_alter_myuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
    ]
