# Generated by Django 4.2.3 on 2023-07-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calldriverapp', '0005_remove_myuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='email',
        ),
    ]
