# Generated by Django 4.2.3 on 2023-07-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calldriverapp', '0007_remove_myuser_is_admin_myuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operationonoff',
            table='operation',
        ),
    ]
