# Generated by Django 4.2.3 on 2023-07-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calldriverapp', '0008_alter_operationonoff_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
